name: Docker Deploy with Trivy

on:
  push:
    branches: ["main"]

jobs:

  trivy_fs_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Trivy (latest stable)
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

      - name: Trivy FS Scan
        run: trivy fs --severity HIGH,CRITICAL .

  docker_image_scan:
    needs: trivy_fs_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          ls -lah
          echo "Building docker image…"
          docker build -t ec2-app:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

      - name: Scan Docker Image
        run: trivy image --severity HIGH,CRITICAL ec2-app:latest

  deploy:
    needs: docker_image_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: ${{ secrets.EC2_PATH }}

      - name: Deploy Docker on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_PATH }}

            echo "Installing Docker on EC2…"
            if command -v apt; then
              sudo apt update -y
              sudo apt install -y docker.io
            else
              sudo dnf install docker -y
            fi

            sudo systemctl start docker
            sudo systemctl enable docker

            echo "Rebuilding Docker Image…"
            sudo docker build -t ec2-app:latest .

            echo "Restarting container…"
            sudo docker rm -f ec2app || true
            sudo docker run -d --name ec2app -p 80:3000 ec2-app:latest
