name: Docker Deploy with Trivy

on:
  push:
    branches: ["main"]

jobs:

  trivy_fs_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy (Official)
        run: |
          sudo apt-get update -y
          sudo apt-get install curl wget apt-transport-https gnupg lsb-release -y
          curl -sfL https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb \
            $(lsb_release -sc) main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install trivy -y

      - name: Trivy FS Scan
        run: trivy fs --severity HIGH,CRITICAL .

  docker_image_scan:
    needs: trivy_fs_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Dockerfile Exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "âŒ Dockerfile missing in ROOT of repo"
            exit 1
          fi

      - name: Build Docker Image
        run: docker build -t ec2-app:latest .

      - name: Trivy Docker Image Scan
        run: trivy image --severity HIGH,CRITICAL ec2-app:latest

  deploy:
    needs: docker_image_scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: ${{ secrets.EC2_PATH }}

      - name: Deploy Docker on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_PATH }}

            echo "Installing Docker..."
            if command -v apt >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y docker.io
            else
              sudo dnf install -y docker
            fi

            sudo systemctl start docker
            sudo systemctl enable docker

            echo "Building Docker image on EC2..."
            sudo docker build -t ec2-app:latest .

            echo "Restarting Docker container..."
            sudo docker rm -f ec2app || true
            sudo docker run -d --name ec2app -p 80:3000 ec2-app:latest
