name: Docker Deploy with Trivy Scan

on:
  push:
    branches: ["main"]

jobs:

  trivy_fs_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      - name: Trivy Filesystem Scan
        run: |
          trivy fs --severity HIGH,CRITICAL .

  trivy_docker_scan:
    needs: trivy_fs_scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ec2-app:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      - name: Trivy Docker Image Scan
        run: |
          trivy image --severity HIGH,CRITICAL ec2-app:latest

  deploy_to_ec2:
    needs: trivy_docker_scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: ${{ secrets.EC2_PATH }}

      - name: Deploy Docker App on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PATH }}

            # Install Docker
            if ! command -v docker &> /dev/null
            then
              echo "Installing Docker..."
              sudo dnf install docker -y 2>/dev/null || sudo apt-get install docker.io -y
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Build Docker image
            sudo docker build -t ec2-app .

            # Stop old container
            sudo docker rm -f ec2-app || true

            # Start new container
            sudo docker run -d --name ec2-app -p 80:3000 ec2-app
